### ISSUE TITLE
Name clash with JavaScript Compiler-Compiler

### ISSUE THREAD

**Issue by lpsantil** [tbusser/jscc#1]
JavaScript Compatibility Checker (shortname "jscc") clashes with the older project, JavaScript Compiler-Compiler (also shortnamed "jscc" or sometimes "js/cc"), [0][1].  Please consider renaming your project to avoid confusion between two great works.  May I suggest ECMAScript Compatibility Checker ("escc") or ECMA-262 Compatibility Checker ("e262cc", "ecc", "262cc").

[0] http://jscc.sf.net/
[1] http://sourceforge.net/projects/jscc/

**Comment by tbusser** [comment]
I am sorry for the short name class but I think it is unavoidable. There are so many projects/organisations that is difficult, if not impossible, to come up with something that isn't in use. If you do a search for JSCC you will also get results for colleges and Japanese organisations.

I do appreciate the alternatives you've come up with but they do not properly reflect what my project does. It detects some of the ECMAScript methods but in addition it also checks for other methods you would use in a browser environment like `querySelector` and `classList`. These are not methods/properties which come from the ECMAScript specification. 

While I am sorry for any confusion the short name clash might generate, I am not going to change domain names at this time.
