### ISSUE TITLE
Unminified JS?

### ISSUE THREAD

**Issue by DrewML** [tbusser/jscc#3]
Any chance you'd be willing to add the unmimified source to the repo? I'd love to help contribute.

**Comment by tbusser** [comment]
Yeah, that is something I'd be willing to do. But before I do that I want to do the following things:
- refactor some shameful bits of code
- add some more comments 
- create a very short style guide for those who are willing to contribute to the project

**Comment by DrewML** [comment]
No problem. Thanks for the hard-work so far. I wouldn't worry too much about the "shameful" bits -- we all have them in our code somewhere :)

Looking forward to the opportunity of helping out and using this in my daily workflow.

**Comment by paulirish** [comment]
### release it, release it, release it!

everybody's source is shameful. just do it dude. :)

**Comment by paulirish** [comment]
In the meantime, the node variant has readable source. https://github.com/tbusser/node-jscc

**Comment by tbusser** [comment]
That was the encouragement I needed ;-)

The source of the project is available, it is in the develop branch of the repository.

**Comment by paulirish** [comment]
Very nice! thanks. :)

If you want to switch default branch in github to that one, you could. But no big deal either way. 

FWIW: 
https://twitter.com/kentcdodds/status/560662873983045632

**Comment by DrewML** [comment]
Thanks @tbusser! I'm excited to start digging through this.
